apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - image: ghcr.io/houssemdellai/containerapps-album-backend:v1
        name: webapi
        ports:
        - containerPort: 3500
